### ISSUE TITLE
加载问题

### ISSUE THREAD

**Issue by jackyzonewen** [jieyou/lazyload#12]
我用了iScroll来滚动，iScroll区域使用可是使用lazyload只能加载首屏的数据，超出的部分滚动的时候不会加载，如果在chrome调试区域修改拉升模拟器屏幕的高度，会触发加载刚刚显示的数据

**Comment by junyug** [comment]
在使用iScroll时，需要在onScrollEnd事件中重新初始化lazyload()

**Comment by jieyou** [comment]
@junyug 感谢你的建议
@jackyzonewen 你的问题解决了吗？
