### ISSUE TITLE
关于加载顺序导致提示找不到jq或者zepto

### ISSUE THREAD

**Issue by semi-xi** [jieyou/lazyload#13]
我在定义这个模块的时候顺序是这样的

``` javascript
  $=require('zepto'),
  lazyload=require('./lazyload.min');
```

但是他还是会提示zepto加载不到的问题。
包括直接用

```
seajs.use(['zepto','lazyload'],function($){
})
```

两种都会提示找不到jq或者zepto的问题

**Comment by jieyou** [comment]
目前源码可能没有对seajs的CMD模式做支持，建议自行修改以下代码尝试：

`
    if(typeof define === 'function' && define.amd){ // AMD
`
去掉`&& defind.amd` 或改为 ` if(typeof define === 'function' && (define.amd || define.cmd))`

**Comment by jieyou** [comment]
@semi-xi 问题解决了吗？如果按照我楼上的方式解决了问题，你可以考虑提交一个pull request

**Comment by semi-xi** [comment]
可以的了~3q

**Comment by jieyou** [comment]
@semi-xi 最终是通过什么办法解决的呢？

**Comment by semi-xi** [comment]
@jieyou  改成cmd的就可以了QWQ~

**Comment by jieyou** [comment]
@semi-xi 能否在你的code中帮忙试一下  if(typeof define === 'function' && (define.amd || define.cmd))   我觉得也是可以用的，如果可以用， 我准备把这句更新到源码，方便其它人
