### ISSUE TITLE
如何让一个不是图片地址的url赋值到图片的src上？

### ISSUE THREAD

**Issue by MrKou47** [jieyou/lazyload#16]
rt，我想实现一个滚动统计的效果，图片的 `data-original` 不是一个图片的路径而是后台服务器的一个get请求的路径。我想让屏幕滚动的时候将这个路径赋值到src上但是并不好使啊，请问这个我该怎么做呢

**Comment by jieyou** [comment]
你的这个统计用图片是0*0的把，或者display为none？这样的话不会触发appear的事件。
你可以简单注释掉源码101行的宽高为0判断即可
https://github.com/jieyou/lazyload/blob/master/lazyload.js#L101

**Comment by MrKou47** [comment]
已经解决，是因为https://github.com/jieyou/lazyload/blob/master/lazyload.js#L279的原因，图片的路径是一个后台的get 请求的url，所以不会触发load的监听回调，我给改成ajax了..

**Comment by jieyou** [comment]
好，感谢关注和使用这个lib
