### ISSUE TITLE
懒加载在浏览器效果ok，在app客户端 webview 中没有效果，图片一下子都加载了，急！

### ISSUE THREAD

**Issue by SuperAL** [jieyou/lazyload#17]
如题

**Comment by SuperAL** [comment]
客户端没有效果的原因为：客户端为了在 web 内容下加上 app 内的评论部分，并使得两者拥有同一个滚动条，在页面加载后将浏览器大小撑开为内容大小，导致所有图片都在浏览器视窗中，因此一次性全部加载了。

**Comment by renrenguiwei** [comment]
同问上面的问题，有解决吗？
