### ISSUE TITLE
当图片不知道宽高的时候不知如何处理

### ISSUE THREAD

**Issue by Webtyj** [jieyou/lazyload#19]
一个商品详情，后台随机编辑上传图片后，只能让图片在手机上宽度100%，高度自适应的情况如何处理？

**Comment by jieyou** [comment]
<style>
        .lazy{width:100%;height:0;padding-top:75%;background-size:100%;}
        /* 假设高宽比为 480:640，即75%，并使用背景图的方式将图片铺在padding-top区域内
        （padding的百分比是宽度的百分比而不是高度的，即使是padding-top|padding-bottom） */
    </style>
    <div class="lazy" data-original="img/example.jpg"><div>
    

文档里面有，试一下
