### ISSUE TITLE
getUnloadElements里面不能正确获取_lazyload_loadStarted属性

### ISSUE THREAD

**Issue by reygreen1** [jieyou/lazyload#24]
https://github.com/jieyou/lazyload/blob/2de2da307bbb1507039aefb3e9fc596379764b8d/lazyload.js#L138

**Comment by reygreen1** [comment]
每个元素的_lazyload_loadStarted属性设置是在$.fn.lazyload方法里面操作的，设置的方式是通过jquery 的eq方法来获取元素。
jquery的eq方法每次调用会创建一个新的jquery对象，所以针对同一个dom使用eq方法获得的jquery对象是不同的，这就是getUnloadElements方法里面不能正确处理_lazyload_loadStarted属性的原因。
修复方式：可以使用data来设置每个元素的_lazyload_loadStarted，$element.data('_lazyload_loadStarted', true)

**Comment by jieyou** [comment]
Fixed in master.
Thanks.
