### ISSUE TITLE
enabled_wide_container例子有问题

### ISSUE THREAD

**Issue by heby** [jieyou/lazyload#8]
enabled_wide_container例子有bug，情况描述如下：
横向滚动，图片没有加载，当触发窗口滚动条，图片才会加载，我测试了竖向，也是这样，滚动container图片不会加载，滚动窗口滚动条才会加载。

**Comment by jieyou** [comment]
感谢提交issue
问题已经定位，明天修复：）

**Comment by jieyou** [comment]
已在新版修复
